export const TODO_ALL_REQUEST = 'TODO_ALL_REQUEST';
export const TODO_ALL_SUCCESS = 'TODO_ALL_SUCCESS';
export const TODO_ALL_FAILURE = 'TODO_ALL_FAILURE';

export const TODO_SINGLE_REQUEST = 'TODO_SINGLE_REQUEST';
export const TODO_SINGLE_SUCCESS = 'TODO_SINGLE_SUCCESS';
export const TODO_SINGLE_FAILURE = 'TODO_SINGLE_FAILURE';